### ISSUE TITLE
python main.py 时报错( python 2.7.13)

### ISSUE THREAD

**Issue by xchl** [jhao104/SSDBAdmin#11]
Traceback (most recent call last):
  File "Run/main.py", line 20, in <module>
    from Api.ProxyApi import run as ProxyApiRun
ImportError: No module named Api.ProxyApi

**Comment by jhao104** [comment]
运行路径不对 到对应文件夹下去跑

**Comment by xchl** [comment]
@jhao104  好了 谢谢
