### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by Tryking** [jhao104/SSDBAdmin#16]
在 kv  页面，当没有选择任何数据的时候，直接点击红色 x 会报错

**Comment by jhao104** [comment]
> 在 kv 页面，当没有选择任何数据的时候，直接点击红色 x 会报错

感谢提醒，已修复此bug https://github.com/jhao104/SSDBAdmin/commit/22b28ab347d637e5036040bb1b0b4755da83fc48
