### ISSUE TITLE
方便加上输入页码跳转吗

### ISSUE THREAD

**Issue by liweiDiao** [jhao104/SSDBAdmin#18]
方便加上输入页码跳转吗？kv那块翻页比较麻烦，有时候key记不太清。

**Comment by jhao104** [comment]
这个要ssdb api 支持才行，kv没有getall的接口，没法做分页

[ssdb api](http://ssdb.io/docs/zh_cn/commands/index.html)

**Comment by liweiDiao** [comment]
哦，这样啊。
