### ISSUE TITLE
zset 报错

### ISSUE THREAD

**Issue by daivvv** [jhao104/SSDBAdmin#6]
![image](https://user-images.githubusercontent.com/38233144/39558545-156f3dd4-4ec2-11e8-90c8-8bf41ca4da43.png)

**Comment by jhao104** [comment]
现在对中文处理还不是很友好 py3支持在开发中

**Comment by daivvv** [comment]
@jhao104 这也是我切换 py3的原因

**Comment by jhao104** [comment]
@daivvv py3现在不支持的

**Comment by vmvz** [comment]
@jhao104 我没有看到 dev分支呀， 我想帮忙早日完成 python3 版本
